### ISSUE TITLE
SSO through brokered authentication not working in android

### ISSUE THREAD

**Issue by Anunest** [stashenergy/react-native-msal#104]
Single sing on using the Microsoft Authenticator app not working in Android.

**Comment by josmithua** [comment]
Yes, `"broker_redirect_uri_registered": true` is not supported at the moment, but it's something I want to get working. Could you post more details, like what error logs you see in logcat?

**Comment by Anunest** [comment]
I have make the broker_redirect_uri_registered value to true in the msal_config.json file and got an error message. Screenshot is attached.
![Errormessage](https://user-images.githubusercontent.com/89453424/130736138-8d1a3443-5f91-40f2-b108-49c8a57adcbf.jpeg)

**Comment by zounasL** [comment]
Have you tried Beta branch, I believe this is fixed in there because you have more freedom to config the MSAL config during runtime?

If I recall correctly this occurred because android MSAL config was missing redirect uri or it was using wrong authority type… I YOLO it and made the MSAL configurable during runtime and in my case the MS Authenticator is working with AzureAD My Organization users. But I recomend to test Beta version

Here is MS doc for the Android MSAL
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration

**Comment by zounasL** [comment]
Have you tried Beta branch, I believe this is fixed in there because you have more freedom to config the MSAL config during runtime?

If I recall correctly this occurred because android MSAL config was missing redirect uri or it was using wrong authority type… I YOLO it and made the MSAL configurable during runtime and in my case the MS Authenticator is working with AzureAD My Organization users. But I recomend to test Beta version

Here is MS doc for the Android MSAL
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration
