### ISSUE TITLE
Android: PublicClientApplications is not initialized.

### ISSUE THREAD

**Issue by tommycp96** [stashenergy/react-native-msal#108]
Hi Joshua,

Hope you doing well, last time after tweak a few scopes config the MSAL library is working fine on my iOS devices.
Unfortunately, I'm facing the below issue on Android even though I already call the `pca.init()` method.
<img width="348" alt="Screen Shot 2021-09-04 at 8 45 26 PM" src="https://user-images.githubusercontent.com/40844706/132096579-430d8f29-5ce5-44f5-9ef3-4aad1b9126ce.png">

FYI I provided my code for my current implementation:

```
class AzureAuthService {
  signInAsync = async () => {
    const pca = new PublicClientApplication(config);
    try {
      await pca.init();
    } catch (error) {
      console.error('Error initializing the pca, check your config.', error);
    }
    const params: MSALInteractiveParams = { scopes };
    const result: MSALResult | undefined = await pca.acquireToken(params);
    return result
  }
}

export default AzureAuthService;
```

and then on my login button I call this class
```
const azureAuth = new AzureAuthService();
const authState = await azureAuth.signInAsync();
```

Thanks!
Best regards,
Tommy

**Comment by zounasL** [comment]
Yo @tommycp96, if you are using v3.1.2 i would suggest to check the msal config.json, i think you have typo in there and that's why it can't initialize the pca.

Link to MS doc about the MSAL config json:
https://github.com/AzureAD/microsoft-authentication-library-for-android#step-2-create-your-msal-configuration-file

Also one mention about your pca declaration. If you want to init the pca later you should add false parameter after config. Check the PublicClientApplication constructor from src folder.

Like this (also mentioned in document):
// Option 2 (RECOMMENDED): Skips init, so you can call it yourself and handle errors
const pca = new PublicClientApplication(config, false);

Here is MS doc for the Android
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration

**Comment by zounasL** [comment]
Ohh, cool that you are using beta.

Maybe if you double check your android setup.

You can also try to use logcat to check if Android will log some errors. Ex. try to filter logcat log with "RNMSALModule"

**Comment by tommycp96** [comment]
Hi @zounasL, after I debug my code and read carefully about the error, I found below errors
```
[Wed Sep 08 2021 11:42:53.653]  ERROR    Error initializing the pca, check your config. [Error: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.]
[Wed Sep 08 2021 11:42:53.785]  LOG      error [Error: PublicClientApplication is not initialized. You must call the `init` method before any other method.]
```

But I already copy-paste the config from my Azure Portal and double-check for the implementation.
Do I need to add the `msal_config` to the android directory file? Because from the beta version seems like I don't need to copy the `msal_config.json` file.

Best regards,
Tommy

**Comment by zounasL** [comment]
No, beauty of the beta version was that you don't need to add that msal_config.json because it is configurable during runtime.

Do you let the app create that redirect uri or have you defined it in config object?
This should be also autogenerated in java side but maybe try to manually set it if you haven't already done so.

https://github.com/stashenergy/react-native-msal/blob/beta/android/src/main/java/com/reactnativemsal/RNMSALModule.java#L94

like: 
`{
  auth: {
    clientId: "your-client-id",
    redirectUri: "msauth://com.{APP}/{HASH",
    .... <- more parameters
  }
}`

can't remember did the hash needed to be url encoded in the config object. When android has managed to serialize the msal config, you should find it from logcat logs when filtering by "RNMSALModule"

**Comment by josmithua** [comment]
Please try setting `broker_redirect_uri_registered` to false in your config, and/or specifying a redirectUri:

```js
const config = {
  auth: {
    ...
    redirectUri: Platform.select({ android: "msauth://com.package/<base_64_url_encoded_signature_hash>", default: undefined })
  }
  androidConfigOptions: {
    broker_redirect_uri_registered: false
  }
}
```

**Comment by tommycp96** [comment]
Hi @zounasL & @josmithua, sorry for my late response. 

I already added this configuration also `broker_redirect_uri_registered: false`.
Is that because I used it on top of the Expo Project?
Or is there any way to use this library in plain JS instead of TypeScript Josh?

**Comment by tommycp96** [comment]
Hi @zounasL and @josmithua, I found out the culprit because I added this config `broker_redirect_uri_registered: false` inside `msal_config.json` instead of from the runtime config. And @zounasL already confirm the beauty of the beta version that we don't need to add manually `msal_config.json` to the Android folder directory.

Now everything is working fine on Android unfortunately after I added `broker_redirect_uri_registered: false` config it won't redirect to the MS Authenticator app like on iOS. May you help to advise how can I redirect to the MS Authenticator app every time I log in using AAD? Or is this the correct behaviour for Android? Because I want our app to be consistent between iOS and Android in terms of user experience.

Best regards,
Tommy

**Comment by zounasL** [comment]
mkay, I might have missed some critical info or something and i apologize for that in advance, but if you wanna use MS Authenticator app you need to set the broker_redirect_uri_registered to true.

Here is my MSAL configuration, which i will pass to PublicClientApplication constructor and MS Authenticator is working for me with both IOS and Android.
```
{
        auth: {
          clientId: "CLIENT_ID",
          authority: `https://login.microsoftonline.com/"TENANT_ID"`,
          redirectUri: Platform.OS === 'ios' ? "REDIRECT_URI_IOS" : "REDIRECT_URI_ANDROID",
        },
        androidConfigOptions: {
            broker_redirect_uri_registered: true,
        }
 }
```

Although i only need to handle scenarios where user is a tenant user, so no external users (haven't tester this kind of scenario yet). So if you are trying to login as external maybe the upcoming pr #110 might fix that.

If not, then i think you are maybe using a "common" authority ( ? ) with single tenant account types selection, which might cause issue? If this is the case i would suggest to try multitenant option.

<img width="889" alt="Screenshot 2021-09-10 at 23 17 23" src="https://user-images.githubusercontent.com/35173117/132912996-6d56c498-d181-4fdf-9bb1-b438f300188f.png">

It is little bit hard to help further, because i don't know your env setup or MSAL config

Hope this will help, @tommycp96

**Comment by tommycp96** [comment]
Hey @zounasL do I need to register the deep link on `AndroidManifest.xml` file like on iOS I need to register the MS Authenticator deep-link to `info.plist`?

**Comment by zounasL** [comment]
I only added the BrowserTabActivity activity in my `AndroidManifest .xml`. So in `AndroidManifest .xml` the signature hash is without any encoding. You need encode the hash in MSAL configuration redirectUri.

Either copy the redirect uri from azure after registering it or encode the hash with js ```encodeURIComponent("3VZgEKh/nEn2TQydm5d....")```

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.*********app">
...
<activity android:name="com.microsoft.identity.client.BrowserTabActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="msauth" android:host="com.*********app" android:path="/3VZgEKh/nEn2TQydm5d.... {REST OF THE  SIGNATURE HASH WITHOUT ANY ENCODING}"/>
            </intent-filter>
        </activity>
```
<img width="1010" alt="Screenshot 2021-09-11 at 10 37 42" src="https://user-images.githubusercontent.com/35173117/132940673-a88457fa-ee5c-4d6c-9efa-a53155a6285e.png">

**Comment by tommycp96** [comment]
I already double check regarding the URI encoded or not for the config. But, even though its already correct whenever I set the `broker_redirect_uri_registered: true` the I got that error. Unfortunately, If I set it as `false` its working perfectly fine without redirect to the Authenticator app. Nvm, let me just close this ticket since its already working for both Android and iOS. Thanks in advance both @josmithua & @zounasL for your help, much appreciate!
