### ISSUE TITLE
Remove account feature not working properly on iOS

### ISSUE THREAD

**Issue by torekymilan** [stashenergy/react-native-msal#3]
Hi @josmithua! After an interactive acquireToken request in our application the users have the chance to logout from B2C using the removeAccount feature. After a successful logout a new acquireToken request does not force the users to provide their credentials again. The WebView appears for a second, but it is closed and login the user automatically. I experienced it only on iOS platform. Maybe the issue derives from the RNMSAL.m file where a new "application" is created (createClientApplicationWithClientId) in the removeAccount method. I tested the example application as well it has the same problem. Thanks a lot in advance.

**Comment by josmithua** [comment]
Hey there @torekymilan, this is a known issue with the Obj-C MSAL library, see:
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/210
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/560. 

For now what I recommend is set the `promptType` option to `MSALPromptType.LOGIN` or `MSALPromptType.SELECT_ACCOUNT` when calling `acquireToken` to force the user to enter credentials again. Let me know if this helps.

I will look into this further when I have some time.

**Comment by josmithua** [comment]
Glad to help! Thanks a lot! Will close this now :)

**Comment by juwilliams** [comment]
Is this issue denoted anywhere else? Ran into this today and could probably help others if this was included as a disclaimer/warning somewhere more visible. Thanks!

**Comment by MuriloDutra** [comment]
Hey guys, how are you? 

I have a similar problem.

When I uninstall my app and install again, the account I was signed-in before uninstalling, remains on the app.
This causes me a problem, because the app thinks there are a signed-user, when it's not. I saw this similar issue, but unfortunately it's related to Xamarin, not react-native: [](https://forums.xamarin.com/discussion/167744/msal-credentials-not-cleared-on-uninstalling-the-app-on-iphonel)

Maybe it's related to keychain? Because this bug only happen on IOS, in Android works fine.
