### ISSUE TITLE
Can't open Microsoft Authenticator app for brokered SSO instead of SSO Enterprise login on iOS

### ISSUE THREAD

**Issue by adityap92** [stashenergy/react-native-msal#47]
I am converting my RN app from ADAL to MSAL, and since the Enterprise SSO login for iOS is still in public preview I do not want to switch over from the Authenticator brokered auth SSO flow. Is this currently supported?

**Comment by josmithua** [comment]
Hi Aditya, I honestly haven't tried before, but if the Android and iOS MSAL libraries support it, then I'd say yes, because this is just a thin wrapper around those libraries.

I know there is an option in the Android config for a brokered flow, so it might very well be possible.

Do try it and let us know the result.

Cheers!

**Comment by adityap92** [comment]
I was able to get it working by using the following webviewParams during interactive login:

ios_webviewType: Ios_MSALWebviewType.SAFARI_VIEW_CONTROLLER
ios_webviewType: Ios_MSALWebviewType.WK_WEB_VIEW
