### ISSUE TITLE
iOS: PublicClientApplication instance not initialized.

### ISSUE THREAD

**Issue by ManishK-Patona** [stashenergy/react-native-msal#79]
I am getting the below error in iOS but it is working fine for Android.
 
Possible Unhandled Promise Rejection (id: 4):
Error: PublicClientApplication instance not initialized.

Can anyone help?

**Comment by josmithua** [comment]
This error will happen if you call a method of the PCA very shortly after calling the constructor. This is because the constructor calls an asynchronous function to initialize the native PCA, so it might not be ready to be used yet. Please read the docs on [creating an instance](https://github.com/stashenergy/react-native-msal#creating-an-instance). With the first option described you have to make sure to create the PCA instance well in advance of when you need it. The second option is better because you can know when it's done initializing and catch any errors.
