### ISSUE TITLE
Attempt to invoke interface method 'void com.microsoft.identity.client.IMultipleAccountPublicClientApplication.acquireToken(com.microsoft.identity.client.AcquireTokenParameters)' on a null object reference

### ISSUE THREAD

**Issue by teeolendo** [stashenergy/react-native-msal#92]
Firstly, my apologies for posting this error, yet again. I've spent days looking for alternatives and the solutions mentioned in #64 and #67 don't work for me. I have reviewed the provided config steps several times to no avail.

I have:
- [x] Upgraded to the latest version of `react-native-msal`
- [x] Read the README thoroughly
- [x] Searched for other similar issues
- [x] Used breakpoint debugging in the Swift/Java module code?
- [ ] Tried to reproduce the problem in the example app in this repository?

**Problem description:**
I'm using version 3.1.1 and I have configured the package as directed for Azure AD Auth. I have ios working just fine but Android fails with the error:

`Error: Attempt to invoke interface method 'void com.microsoft.identity.client.IMultipleAccountPublicClientApplication.acquireToken(com.microsoft.identity.client.AcquireTokenParameters)' on a null object reference`

After reviewing #67 and #64 , I only call the pca.AcquireToken after pca.isInitialized is true. 
```tsx
if (pca.isInitialized){
  const result: MSALResult = await pca.acquireToken(params);
  console.log(result);
}
```

I have added the msal_config.json to `android/app/src/main/res/raw/msal_config.json` and `android/app/src/main/assets/msal_config.json` with no effect.

Breakpoint debugging doesn't seem to work in spite my greatest efforts but I logged the Java acquireToken method and I can confirm that the scope is being passed to the method but it still fails.

**Contents of `msal_config.json`:**
```json
{
  "client_id" : "xxxxxxx",
  "authorization_user_agent" : "DEFAULT",
  "redirect_uri" : "msauth://org.congressgct.sensapg/pyLoXTtb0xxxxxxxxxx",
  "account_mode": "MULTIPLE",
  "broker_redirect_uri_registered": true,
  "authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADMyOrg",
        "tenant_id": "xxxxxxxx"
      }
    }
  ]
}
```

**Relevant contents of `AndroidManifest.xml`:**
```xml
<activity android:name="com.microsoft.identity.client.BrowserTabActivity">
  <intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="msauth" android:host="org.congressgct.sensapg" android:path="/pyLoXTtb0xxxxxxxx" />
  </intent-filter>
</activity>
```

**Usage JavaScript/TypeScript code:**
```tsx
const signIn = async () => {
  const config: MSALConfiguration = {
    auth: {
      clientId: AZURE_CLIENT_ID,
      authority:
        'https://login.microsoftonline.com/<tenantid>',
    },
  };
  const pca = new PublicClientApplication(config, false);
  try {
    await pca.init();
  } catch (error) {
    console.error('Problem in configuration/setup:', error);
  }

  const params: MSALInteractiveParams = {
    scopes: ['User.Read'],
  };
  try {
    if (pca.isInitialized){
      const result: MSALResult = await pca.acquireToken(params);
      console.log(result);
    }
  } catch (error) {
    handleError(error);
  }
};
```

**Relevant error messages and screenshots:**
Error: Attempt to invoke interface method 'void com.microsoft.identity.client.IMultipleAccountPublicClientApplication.acquireToken(com.microsoft.identity.client.AcquireTokenParameters)' on a null object reference

**Comment by paulorod07** [comment]
@teeolendo Did You find any solution? 
I am getting the same problem

**Comment by josmithua** [comment]
This happens when you have `"broker_redirect_uri_registered": true` in your `msal_config.json`. If you don't need it, please set it to `false`. If you do, unfortunately I don't know what to do at the moment. I can try to look into it at some point, but not sure when I'll have time. Same issue as #90

**Comment by teeolendo** [comment]
Thanks @josmithua for the tip. I turned `"broker_redirect_uri_registered": false` and nothing it didn't change anything unfortunately. Maybe @paulorod07 has had better success?

**Comment by RichardNolan** [comment]
I'm having this same issue. Taking the provided class for B2C directly as is, I'm getting an error on getAccounts on null. I have delayed the init. If I sign-in rather than acquire token silent I get this exact error. But when I substitute the clentId, authority, etc in both msal_config.json and my own config with those from the demo it works perfectly. 
I know the simple answer would be that its a problem on my B2C, but I can't see where. I set up everything using defaults or the most basic config possible and I keep getting this error. Is there something specific about the B2C setup that I'm missing?

**Comment by estebanInnventto** [comment]
@teeolendo @paulorod07 Were you able to solve this issue or found a workaround? I have the same problem

**Comment by staff0rd** [comment]
I was getting this error for a bunch of different failures, tracked it back to [this line](https://github.com/stashenergy/react-native-msal/blob/f01a4b4aaf9362c028a32f3417e95fcbe4b9d89b/android/src/main/java/com/reactnativemsal/RNMSALModule.java#L57-L58) where auth exceptions are being swallowed.

By logging that exception with something like:
```java
} catch (Exception ignored) {
    System.out.println(ignored);
}
```
and viewing logcat, I can see the actual MSAL error ocurred, for example:

> 2021-07-20 11:56:07.557 15736-15851/au.com.mycompany.myapp I/System.out: com.microsoft.identity.client.exception.MsalClientException: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.

I could open a PR for this change but, it would likely be better to return this error to React Native instead of needing logcat, so I would question why it's being swallowed to start with.

**Comment by josmithua** [comment]
@staff0rd Oops, this was introduced in an external PR, will release a patch version soon with this fixed

**Comment by josmithua** [comment]
[v3.1.2](https://github.com/stashenergy/react-native-msal/releases/tag/v3.1.2) should surface these errors if you use:

```js
const pca = new PublicClientApplication(config, false);
try {
  await pca.init();
  // now you can use other functions i.e. pca.acquireToken(...)
catch (error) {
  console.error(error);
}
```

**Comment by stafford-woodside** [comment]
Tested 3.1.2 - error now surfaced in React Native, thanks very much.

**Comment by staff0rd** [comment]
Tested in 3.1.2, error now surfaced in React Native, thank-you!
