### ISSUE TITLE
Refresh token expiring in 12 hours due to MSAL not providing the device id under "DeviceAuth:PkeyAuth" to AAD.

### ISSUE THREAD

**Issue by aditya38112** [stashenergy/react-native-msal#97]
So, we recently migrated to MSAL using react-native-msal for our react-native app to resolve the refresh token expiry issue and that issue is still occurring due to MSAL not providing under "DeviceAuth: PkeyAuth" to AAD, which is used to check whether the device is compliant or not and then if it is non-compliant, it forces the refresh token to get expired in 12 hours.

We have raised the issue with MSAL and AAD team and according to their information, I am opening the issue here.

The issue can be observed easily by using our app, and then observing that after 12 hours again a login is required due to the expiration of the refresh token.

The expected behavior is for compliant devices token should not expire

 - `react-native-msal` version: 3.1.0
 - `react-native` version: 0.62.2
 - Platform: Android, IOS

**Comment by josmithua** [comment]
So you were seeing this issue even before you switched to React Native and the react-native-msal library?

**Comment by aditya38112** [comment]
So, we got the token expiry issue from March-end, and the resolution for that was to move to MSAL, (https://stackoverflow.microsoft.com/questions/252405), so yes the issue was still coming in the previous ADAL implementation, and the issue is still there now.

**Comment by aditya38112** [comment]
@josmithua, Is there any possible solution from your side, as it is affecting our customer experience and we need to resolve this as soon as possible?

**Comment by josmithua** [comment]
@aditya38112 Unfortunately not. I will admit I honestly don't know anything about PkeyAuth/ADFS. But if the same issue was occurring before you switched to this library, then the issue is most likely not with this library. This is just a very thin wrapper around the native Android and iOS MSAL libraries that Microsoft provides. If you have a problem with functionality, it's most likely with them. Not saying this library is bug free (we are on v3.0.2 after all), but it sounds clear to me that the issue lies elsewhere.

**Comment by aditya38112** [comment]
Okay, Thanks for the response, I will try to get it resolved from them.
